### PR TITLE
fix: using empty image label for container metrics

### PR DESCRIPTION
**Pull request by dotdc**
# Pull Request

### :mag_right: What kind of change is it?

- fix

### :dart: What has been changed and why do we need it?

- Switch label filter `image!=""` to `image=""` on `container_*` metrics

We need this because it seems slightly more accurate and avoids a bug where memory get doubled.

Users should expect a small TSDB data change like in the graph below:

2024-09-30 21 25 49 localhost 4e2725020521

### :heavy_check_mark: Which issue(s) this PR fixes?

- N/A

### CODE REVIEW

**Comment by buroa** [comment]
Hey @dotdc this seemed to break all my dashboards in my environment. Can we please revert this?

**Comment by onedr0p** [comment]
Can confirm these dashboards don't show any data with this change. Please revert.

**Comment by onedr0p** [comment]
- Talos 1.8.0
- Kubernetes 1.31.1
- kube-prometheus-stack 65.0.0

**Pull request merged**
