### PR TITLE
feat: ignore template characters in dashboards

### PR DESCRIPTION
**Pull request by jcpunk**
# Pull Request

### :mag_right: What kind of change is it?

- feat

### :dart: What has been changed and why do we need it?

- When including this repo as a git submodule, it is hard to isolate template objects from non-template ones.  This tells the template engine that these are not to be rendered.

### :heavy_check_mark: Which issue(s) this PR fixes?

- https://github.com/kluctl/kluctl/issues/418

### :speech_balloon: Additional information?

- My deployment has a few layers of templates to simplify parameterization, being able to say "no don't treat `{{ }}` as parameter elements" makes including these dashboards in my system much easier.

### CODE REVIEW

**Comment by dotdc** [comment]
Hi @jcpunk,

Can't you create this file in your repository at an upper level?

Example:
```
grafana-dashboards-kubernetes/dashboards/*.json
```

**Comment by dotdc** [comment]
According to https://github.com/kluctl/kluctl/issues/418#issuecomment-1515983188, you should be able to that in your own repo.

I would prefer this solution to avoid including code used by external use-cases.

Let me know if that works for you.

**Comment by jcpunk** [comment]
I can go that route; I was merely hopeful to give something back to the project.  But if you don't think it will help anyone else, I'm fine to abandon this PR.

**Comment by dotdc** [comment]
Apparently it doesn't work yet...
I'll merge this PR while waiting for the [kluctl fix](https://github.com/kluctl/kluctl/issues/418#issuecomment-1516873871) from @codablock.

Also curious to see if adding a file to the dashboards folder affects other external use-cases.

You already helped both this project and kluctl by creating this request, we now know how to exclude these and a bug is going to be fixed on kluctl side! 😉 

Just so you know, I may delete the `.templateignore` file in this project once it's fixed on kluctl.

Thank you for your contribution!

**Pull request merged**
