### PR TITLE
Make trivy operator dashboard colors more consistent

### PR DESCRIPTION
**Pull request by cmergenthaler**
# Pull Request

### :mag_right: What kind of change is it?

- feat

### :dart: What has been changed and why do we need it?

- It makes colors in trivy-operator dashboard more consistent over the different panels (e.g. in timeseries critical was green)
- It also changes colors for
  - critical = dark red
  - high =red
  - medium = orange
  - low = yellow

### CODE REVIEW

**Comment by dotdc** [comment]
Hi @cmergenthaler,

I didn't have time to test the updated dashboard yet, but I'm pretty sure I'd rather keep the current color scheme for vulnerabilities (red, orange, yellow and blue).
While I understand why you could prefer dark-red and red for critical and high vulnerabilities, I think that it will reduce the overall readability of the dashboard.

I'll double check this next week and let you know!

**Comment by cmergenthaler** [comment]
Hi @dotdc,

Thanks for your feedback. Although I personally don't like to use blue as color in traffic light based panels, I can totally understand the usage here. If that is a blocker for the PR, I can also revert the color changes for the severities.
Anyways I think the change regarding consistency over all panels would still be beneficial here.

**Comment by dotdc** [comment]
Hi @cmergenthaler,

I tried your version and I like :
- the new panel order : critical-high-medium-low instead of low-medium-high-critical
- the custom color overrides in the timeseries panels

Can you just rollback to the original colorscheme (red-orange-yellow-blue) in all the panels?

I think we can merge once it's done.

**Comment by cmergenthaler** [comment]
@dotdc done

**Comment by dotdc** [comment]
Thank you for your contribution!

**Pull request merged**
