### PR TITLE
Adding compatibility with default scrape_configs

### PR DESCRIPTION
**Pull request by beliys**
Adding compatibility with default scrape_configs:

https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L783
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-agent/values.yaml#L293

### CODE REVIEW

**Comment by dotdc** [comment]
Hi @beliys,

Do you have `kubernetes-apiservers` as a value in the `job` label?
Could you share more information on your setup?

If it's the case, I would rather create a `job` variable like it was the case before.
Let me know if you need help.

**Comment by beliys** [comment]
Hi @dotdc,
That's right, `kubernetes-apiservers` is the default value if you don't install it through `kube-prometheus-stack` or `victoria-metrics-k8s-stack`. And if you install this chart https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus or this https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-agent, then you have` job=kubernetes-apiservers`. Of course, I can override all the rules in the default `scrape_configs`, but if this PR is not suitable, then it's easier for me to just fork this dashboard. But if you accept this PR, it will allow you to use your dashboard in all standard cases, not just when using `kube-prometheus-stack` or `victoria-metrics-k8s-stack`.

**Comment by dotdc** [comment]
Sure, will probably create a job variable at some point.
Thank you for your contribution!

**Pull request merged**
