### PR TITLE
fix: unreadable panels with light background

### PR DESCRIPTION
**Pull request by clementnuss**
#27

# Pull Request

### :mag_right: What kind of change is it?

- fix 

### :dart: What has been changed and why do we need it?

- the color of some `Stat` panels was changed to `none`, to make it visible for users of Grafana light background

### :heavy_check_mark: Which issue(s) this PR fixes?

- #27

### CODE REVIEW

**Comment by dotdc** [comment]
Works!
Could you please bump the dashboard version on each of theses?

**Comment by clementnuss** [comment]
avec plaisir !

**Review by dotdc — APPROVED** [review]
LGTM

**Comment by dotdc** [comment]
Thank you for your contribution! :blush:

**Pull request merged**
