### PR TITLE
fix(k8s-views-namespaces): filter metrics to prevent reporting double cpu/memory

### PR DESCRIPTION
**Pull request by uhthomas**
# Pull Request

### :mag_right: What kind of change is it?

- fix

### :dart: What has been changed and why do we need it?

Most queries already use label matcher. The metric reports usage for each individual image, and the whole pod which will result in incorrect reporting if not filtered correctly.

### :heavy_check_mark: Which issue(s) this PR fixes?

Fixes: #60

### :speech_balloon: Additional information?

I'm using `=` rather than `!=` as it should be more efficient to fetch only the needed metrics rather than individual metrics for each image. I don't think Grafana does any deduplication, so I don't imagine the same query in multiple places will be beneficial. I could be wrong.

### CODE REVIEW

**Comment by uhthomas** [comment]
Before

image

After

image

**Comment by dotdc** [comment]
Hi @uhthomas,

Thanks for the fix, I noticed the issue but didn't had time to look into it.
I understand and agree on your point of using `=` rather than `!=`, but I don't know if the `image=""` series get created on all setups. I feel like their could be cases where the `image=""` series doesn't exist or get dropped, but I could be wrong...
Do you know anything about that? 

Currently, all PromQL queries like that are on this format, so I would rather keep them like that for consistency, unless we are confident it will not break for some users, in which case, we could change them all. 

Let me know.

**Comment by uhthomas** [comment]
@dotdc I don't really have a preference. I think there are advantages to both. The label selector `image=""` should be more efficient as it should be working with fewer overall metrics. Though keeping it the same as all the other queries could actually be better due to caching.

With respect to your question about whether it's safe to use, I believe it is. A cursory search across GitHub doesn't seem to show any instances of this metric being dropped at all.

https://github.com/search?q=container_cpu_usage_seconds_total+image+action%3A+drop+language%3AYAML&type=code

**Comment by dotdc** [comment]
I'll merge this as is because I like your approach better. Will uniform later if there's no side effects.

Thanks @uhthomas !

**Comment by dotdc** [comment]
@uhthomas
Just switched back to `!=` because it can lead to issues on some setups.
See: https://github.com/dotdc/grafana-dashboards-kubernetes/issues/62

**Pull request merged**
