### PR TITLE
fix: dashboard showing metrics from nodes outside of kubernetes cluster

### PR DESCRIPTION
**Pull request by tlemarchand**
# Pull Request

### :mag_right: What kind of change is it?

- fix

### :dart: What has been changed and why do we need it?

- Currently the global views show metrics from all nodes. If Prometheus is used to gather metrics from nodes that are not part of the kubernetes cluster, the metrics showed are wrong. This PR fixes this problem. Also, it increase coherence with line 332 which already includes such a filter.

### :heavy_check_mark: Which issue(s) this PR fixes?

- ...

### :speech_balloon: Additional information?

- ...

### CODE REVIEW

**Review by dotdc — APPROVED** [review]
LGTM

**Comment by dotdc** [comment]
Thank you for your contribution @tlemarchand !

Just to know, do you have the same problem on the node view?

**Comment by tlemarchand** [comment]
@dotdc : no problem on the node view, only nodes from cluster are shown.

Thank you for theses dashboards, very useful.

**Pull request merged**
