### PR TITLE
Make Detaillled CVE vulnerabilities table filterable

### PR DESCRIPTION
**Pull request by rcattin**
# Pull Request

### :mag_right: What kind of change is it?

-  feat

### :dart: What has been changed and why do we need it?

- add filter on Detaillled CVE vulnerabilities table 

### :heavy_check_mark: Which issue(s) this PR fixes?

- ...

### :speech_balloon: Additional information?

- ...

### CODE REVIEW

**Comment by dotdc** [comment]
Hi @rcattin,
LGTM, could you just bump the dashboard version at the end of the file?

**Comment by rcattin** [comment]
Done, ty for the dashboards btw !

**Review by dotdc — APPROVED** [review]

**Comment by dotdc** [comment]
Thank you for your contribution! :tada:

**Pull request merged**
