### PR TITLE
feat(k8s-views-global.json): added cluster variable

### PR DESCRIPTION
**Pull request by dotdc**
# Pull Request

### :mag_right: What kind of change is it?

- feat

### :dart: What has been changed and why do we need it?

- Added the ability to filter on cluster when it's in use

### :heavy_check_mark: Which issue(s) this PR fixes?

- Linked to #15

### CODE REVIEW

**Comment by jkroepke** [comment]
cluster as multi-values field is not an good idea.

The if there is the same namespace on multiple clusters (e.g. `kube-system`, `flux-system`), the `CPU Utilization by namespace` chart shows very high values.

Instead: `sum(rate(container_cpu_usage_seconds_total{image!="", cluster=~"$cluster"}[$__rate_interval])) by (namespace)`, use `sum(rate(container_cpu_usage_seconds_total{image!="", cluster=~"$cluster"}[$__rate_interval])) by (cluster, namespace)` and adjust the legend `{{ cluster }} {{ namespace }}` or disallow multi-value of cluster.

**Comment by dotdc** [comment]
Disabled multi for the `cluster` variable, as it's a less intrusive change for now.

**Review by jkroepke — APPROVED** [review]
LGTM

**Pull request merged**
